### ISSUE TITLE
Is this fork independent?

### ISSUE THREAD

**Issue by t-mart** [Stanzilla/vscode-wow-toc#2]
Hey there @Stanzilla,

What's the status on this fork, with regards to it be merged back into https://github.com/Septh/vscode-wow-bundle?

I actually wrote a little PR against Septh's repo that improved the toc highlighting for localized keywords (requiring a valid locale code like `## Notes-deDE`, instead of any hypothetical `## Notes-xxXX`). Then, by accident, I actually installed your extension, only to realize that this work had already been done.

It's confusing to have 2 forks of a project available on the extension marketplace. In particular, the documentation is an excerpt of Septh's project and the badge URL and version number both refer back to that project as well.

![wow-toc-ext](https://user-images.githubusercontent.com/200012/109828907-b0079d80-7c02-11eb-9af0-d003c842b852.png)

```markdown
[![GitHub](https://img.shields.io/github/release/Septh/vscode-wow-bundle.svg?style=flat-square)](https://github.com/Septh/vscode-wow-bundle/releases)
```

Do you have any plans to merge back? Or conversely, plans to disambiguate the project? I might be able to help you with the README.md if so, like:

- Changing that badge URL and badge version number
- Adding an explicit source code link to this project, and/or calling out that this is a fork of the other project with a more focused feature set (seems to be just TOCs)
- Updating the demo screenshot to use your toc highlighting color scheme
- Doing a rough pass on the readme to make it more distinct

(For what it's worth, I started some work last night on adding TOC file name completion and diagnostic "squiggly red underlining" for files that do not exist. I suppose if I had to choose an upstream for that work, it'd be *this* project because of its greater focus on TOC files.)

**Comment by Stanzilla** [comment]
It's independent yeah because I only wanted the TOC features. it's a really low effort "fork" and I should probably have invested more time into it. I would love to get improvements but considering your time and effort it's probably better as a PR to Seph? If you use both the TOC and Lua features? If not, I'd be happy to take it. Also would be happy to take README changes if you want to put the time in.

**Comment by t-mart** [comment]
Let me think about that.

This fork has stronger TOC features and less surface area without Lua support, which may actually be a good thing because the WoW API is a moving target, but a smaller userbase.
